# Generated by Django 2.0.12 on 2020-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('ProductDes', models.CharField(max_length=500)),
                ('create_ts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
