# Generated by Django 2.0.12 on 2020-01-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='productCostPrice',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='product_details',
            name='productRetailPrice',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
